import os
import asyncio
import time
import requests
from pyrogram import Client, filters
from yt_dlp import YoutubeDL

API_ID = 29169428
API_HASH = '55742b16a85aac494c7944568b5507e5'
BOT_TOKEN = '8006815965:AAEQ2wkjCr8iKm78SiPc03QzQY_t33CxOeo'

MAX_DURATION = 30 * 60

COOKIES_CONTENT = """# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
#HttpOnly_.youtube.com	TRUE	/	TRUE	1806240494	__Secure-3PSID	g.a0007AgJHBHSErMRvS4H0ua9230sbVZhL58ZPqfQos5GsZ7ZvUhgXNXCKGRqECnNoW2Tw5_O9wACgYKAdASARUSFQHGX2Mipl8lKXM1CVnATF9k9rVLgBoVAUF8yKqr2yb505ay2Tae-nIZ_OSn0076
.youtube.com	TRUE	/	FALSE	1803216678	SIDCC	AKEyXzX19gSyURKnxMofX72khLqieymNEskJB6f-mJaJsxyR6HsKQGscPp4mjZDrPQ3g26RL
.youtube.com	TRUE	/	FALSE	1806240494	SID	g.a0007AgJHBHSErMRvS4H0ua9230sbVZhL58ZPqfQos5GsZ7ZvUhg2OgohLAUtpCk5aLpoQMaIQACgYKAdISARUSFQHGX2Mih0fxRWS9ZdmtaBsJfP-RcBoVAUF8yKrBWFALKY04UsI8pDFQtTwo0076
#HttpOnly_.youtube.com	TRUE	/	TRUE	1803216494	__Secure-1PSIDTS	sidts-CjQBBj1CYjDvCWjLG2pLx_67JFYIeEgHfyjEyaBuBaHQP3vWxKU9LmS70WoaDUdmNWcjqZchEAA
.youtube.com	TRUE	/	TRUE	1806240494	SAPISID	xsSbV-G9TTss6j55/AU5zCCoBq8-JUjbLe
#HttpOnly_.youtube.com	TRUE	/	TRUE	1803216678	__Secure-1PSIDCC	AKEyXzUWHXscvGazCfvNUnaYYro48SNIcu-AOPfHK4t9SbmdeFDEn5sDFerNTbipHcYOwKGD
#HttpOnly_.youtube.com	TRUE	/	TRUE	1806240494	SSID	A-rIetakyJAbykoxU
.youtube.com	TRUE	/	TRUE	1806240494	__Secure-1PAPISID	xsSbV-G9TTss6j55/AU5zCCoBq8-JUjbLe
#HttpOnly_.youtube.com	TRUE	/	TRUE	1806240494	__Secure-1PSID	g.a0007AgJHBHSErMRvS4H0ua9230sbVZhL58ZPqfQos5GsZ7ZvUhgKDNNCihMf-R1OZXj7kOFBQACgYKAaoSARUSFQHGX2MiCf84cg4xXlaN-Hvao6SMqxoVAUF8yKpsDh7__T_7-hNjZN0qS15v0076
.youtube.com	TRUE	/	TRUE	1806240494	__Secure-3PAPISID	xsSbV-G9TTss6j55/AU5zCCoBq8-JUjbLe
#HttpOnly_.youtube.com	TRUE	/	TRUE	1803216678	__Secure-3PSIDCC	AKEyXzUACeAnb78BO_TKgFtvC54-9z1fVjdT_OpPvlqORdJUAwmnh40e9yasL8P9EwTKK5QElg
#HttpOnly_.youtube.com	TRUE	/	TRUE	1803216494	__Secure-3PSIDTS	sidts-CjQBBj1CYjDvCWjLG2pLx_67JFYIeEgHfyjEyaBuBaHQP3vWxKU9LmS70WoaDUdmNWcjqZchEAA
.youtube.com	TRUE	/	FALSE	1806240494	APISID	ZnF8MlCEnPNL3bf6/AVFQPY8sQfuT8GLAN
#HttpOnly_.youtube.com	TRUE	/	FALSE	1806240494	HSID	Asqtw9CzJAY9RI-jp
#HttpOnly_.youtube.com	TRUE	/	TRUE	1806240528	LOGIN_INFO	AFmmF2swRAIgSCWCeNTxZ0RLnEQNIVMQKiDKUrWWNEIHTTXVtcBfGagCIEAFox7WZGJFrpn4VuSe5ACRFw4Pd7_N6xcaBrrNnLIE:QUQ3MjNmeHM3cXVrLWxoNFJleDBfNndaS1ZqS2dlaC1HdGFJVUlzUW9LOGFjamhHcTdfeGZkTlJ2X_V6NWE2WjZZSzBkZ21ESG9jSlZzTnVtZWdvV0dpT2VKX1FtOHlSeUpRWVFpcmRWSEdkOVF3YUlPd0ZqbnFNSENzaXVHOS1fVVRfSGJ5X0dyMjVoNnBBRGViYTNlVDN3ak9HLXpSNDJn
.youtube.com	TRUE	/	TRUE	1806240675	PREF	f4=4000000&tz=Africa.Nairobi
"""

with open('cookies.txt', 'w') as f:
    f.write(COOKIES_CONTENT)

app = Client(
    "video_dl_bot",
    api_id=API_ID,
    api_hash=API_HASH,
    bot_token=BOT_TOKEN,
    workers=20
)

YDL_OPTS_YOUTUBE = {
    'format': 'best[ext=mp4]/best',
    'outtmpl': 'video_%(id)s.%(ext)s',
    'quiet': True,
    'no_warnings': True,
    'cookiefile': 'cookies.txt'
}

YDL_OPTS_PINTEREST = {
    'format': 'best',
    'outtmpl': 'video_%(id)s.%(ext)s',
    'quiet': True,
    'no_warnings': True
}

YDL_OPTS_DEFAULT = {
    'format': 'best',
    'outtmpl': 'video_%(id)s.%(ext)s',
    'quiet': True,
    'no_warnings': True,
    'cookiefile': 'cookies.txt'
}

def extract_metadata_from_info(info):
    width = info.get("width")
    height = info.get("height")
    duration = info.get("duration")
    if not width or not height:
        formats = info.get("formats") or []
        for f in formats:
            if f.get("width") and f.get("height"):
                width = f.get("width")
                height = f.get("height")
                break
    return width, height, duration

def download_thumbnail(url, target_path):
    try:
        resp = requests.get(url, stream=True, timeout=15)
        if resp.status_code == 200:
            with open(target_path, "wb") as f:
                for chunk in resp.iter_content(chunk_size=8192):
                    if chunk:
                        f.write(chunk)
            if os.path.exists(target_path):
                return target_path
    except Exception:
        pass
    return None

def pick_opts(url):
    if "youtube.com" in url or "youtu.be" in url:
        return YDL_OPTS_YOUTUBE
    if "pinterest.com" in url:
        return YDL_OPTS_PINTEREST
    return YDL_OPTS_DEFAULT

@app.on_message(filters.command("start") & filters.private)
async def start(client, message):
    await message.reply_text("""Welcome 👋

This bot lets you download videos from
YouTube, TikTok, Instagram, and more.

 💎 devloper by @laki3012

👉 Just send the video link""", quote=True)

@app.on_message(filters.private & filters.text)
async def handler(client, message):
    url = message.text.strip()
    if not url.startswith(("http://", "https://")):
        return

    msg = await message.reply_text("⏳ Processing...", quote=True)

    try:
        loop = asyncio.get_event_loop()
        ydl_opts = pick_opts(url)

        with YoutubeDL(ydl_opts) as ydl:
            info = await loop.run_in_executor(None, lambda: ydl.extract_info(url, download=False))

            duration = info.get("duration")
            if duration and duration > MAX_DURATION:
                await msg.edit("Zxp masoo dajin kari Video ka dheer 30 daqiiqo. Beta ayaan ku jiraa.")
                return

            info = await loop.run_in_executor(None, lambda: ydl.extract_info(url, download=True))
            filename = ydl.prepare_filename(info)

        await msg.edit_text("📤 Uploading...")

        caption = info.get('title', 'Video')
        if info.get('description'):
            caption = info.get('description')[:1024]

        width, height, duration = extract_metadata_from_info(info)

        thumb_path = None
        thumb_url = info.get("thumbnail")
        if thumb_url:
            temp_thumb = f"thumb_{info.get('id')}.jpg"
            thumb_path = download_thumbnail(thumb_url, temp_thumb)

        await app.send_video(
            chat_id=message.chat.id,
            video=filename,
            caption=caption,
            thumb=thumb_path,
            width=width if width else 0,
            height=height if height else 0,
            duration=int(duration) if duration else 0,
            reply_to_message_id=message.id
        )

        if os.path.exists(filename):
            os.remove(filename)
        if thumb_path and os.path.exists(thumb_path):
            os.remove(thumb_path)

        await msg.delete()

    except Exception as e:
        error_message = f"❌ Error: {str(e)}"
        await msg.edit(error_message[:4096])

if __name__ == "__main__":
    app.run()
